[ui]
editor = "nvim"
# diff-editor = "vimdirdiff"
# diff-formatter = ":git"
default-command = "-h"

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[user]
name = "Noah Bogart"
email = "noah.bogart@hey.com"

[revset-aliases]
"open()" = "(mine() ~ ::trunk()) ~ heads(empty())"

[git]
write-change-id-header = true

[templates]
git_push_bookmark = '"nb/push-" ++ change_id.short()'
