[ui]
editor = "nvim"
diff-editor = "vimdirdiff"
diff.format = "git"
default-command = "-h"

[revsets]
log = "::@"

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[user]
name = "Noah Bogart"
email = "noah.bogart@hey.com"

[revset-aliases]
"open()" = "(mine() ~ ::trunk()) ~ heads(empty())"

[git]
push-branch-prefix = "nb/push-"
