ui.editor = "nvim"
ui.diff-editor = "vimdirdiff"
ui.diff.format = "git"

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[user]
name = "Noah Bogart"
email = "noah.bogart@hey.com"
