ui.editor = "nvim"
ui.diff-editor = "vimdirdiff"
ui.diff.format = "git"
ui.default-command = "log"

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[user]
name = "Noah Bogart"
email = "noah.bogart@hey.com"

revset-aliases."immutable_heads()" = "main@origin | (main@origin.. & ~mine())"
